# Generated by Django 4.2.9 on 2024-01-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
