# Generated by Django 4.2.9 on 2024-01-31 06:00

from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_alter_post_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=post.models.upload_image)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.post"
                    ),
                ),
            ],
        ),
    ]
