# Generated by Django 4.2.9 on 2024-01-31 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_remove_post_image_postimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postimage",
            old_name="image",
            new_name="images",
        ),
    ]
