# Generated by Django 4.2.9 on 2024-01-31 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_rename_image_postimage_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postimage",
            old_name="images",
            new_name="image",
        ),
    ]
